apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes: 
    # "ReadWriteOnce" means vol can me mounted as RW by a signle node
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  # default storageclass is used if none specified
  #storageClassName: admstor
  